Checkout deez updates yo
purdue-arc/purdue-arc.github.io pull request #4
Opened 2020-07-10 18:42 UTC by hmcty

2020-07-13 01:09 UTC, jrbaxter0 commented on _data/sponsors.yml
> +#  url:
Do you think we should remove the sponsorship tiers? Maybe looks bad that we only have bronze sponsors... Also, IDK if mynt is actually a sponsor, they gave us a discount one time.

2020-07-13 01:11 UTC, jrbaxter0 commented on _pages/index.md
> +### Covid-19 Update
This might fit better under news. Also, COVID-19 should be capitalized. In your first sentence, you use third person, then first person possessive in the same clause, which I think sounds off.

2020-07-13 01:12 UTC, jrbaxter0 commented on _posts/2019-02-08-iarc.md
> +Unfortunately, The 7th mission of the IARC concluded in the summer of 2018. At this point ARC moved onto its current project, the [Autonomous RC Car]({{site.url}}\projects\car\)
nice fix. We should also add mission 9 and our other projects. separate PR for that though.

2020-07-13 01:15 UTC, jrbaxter0 commented on _posts/2020-07-10-f20_callout.md
> +In consideration of recent events with Covid-19, Purdue ARC has decided to host the Fall 2020 callout virtually. Upon release, students will be able to view the callout in an uploaded YouTube video a
same comment about capitalizing COVID. Also, it was my understanding we would do a live, webex hosted callout, plus post a pre-recorded one to YouTube at around the same time. Did you come up with the 17th arbitrarily? 28th maybe seems like a better date.

2020-07-13 01:17 UTC, jrbaxter0 commented on rundocker_bash.sh
> +#!/bin/bash
you can just modify the other file if you want. You could make it called by `./rundocker.sh bash` if you want to be fancy.

2020-07-13 01:20 UTC, jrbaxter0 requested changes
At a minimum, there are some minor grammatical things (COVID, not Covid), and info on the callout that need to be updated.

2020-07-18 18:03 UTC, hmcty commented on _data/sponsors.yml
> +#  url:
Just deleted tiers because I agree

2020-07-18 18:06 UTC, hmcty commented on _posts/2020-07-10-f20_callout.md
> +In consideration of recent events with Covid-19, Purdue ARC has decided to host the Fall 2020 callout virtually. Upon release, students will be able to view the callout in an uploaded YouTube video a
I came up with the 17th randomly just to put a date on when we should release the youtube video by. If you wanted, we could do an additional webex callout that's hosted on the 28th.

2020-07-18 18:07 UTC, hmcty commented on _posts/2020-07-10-f20_callout.md
> +In consideration of recent events with Covid-19, Purdue ARC has decided to host the Fall 2020 callout virtually. Upon release, students will be able to view the callout in an uploaded YouTube video a
I figured we should get the video posted early so that students can find it before coming to campus

2020-07-18 18:08 UTC, hmcty commented on rundocker_bash.sh
> +#!/bin/bash
Agreed

2020-07-18 18:20 UTC, hmcty commented on _pages/index.md
> +### Covid-19 Update
Fixed weird writing, but I'm not sure if it belongs under news because it's a temporary change for the club and we want them to be aware as soon as they visit the site. If anything we could add an additional news post, but we should definitely still have a message active on the home page.

2020-07-18 18:21 UTC, hmcty commented
Look over some of the changes and fixes, then let me know if there is anything else I can do

2020-07-19 04:11 UTC, jrbaxter0 commented
please verify that my changes to the Docker script didn't break anything for you. There's a sort of weird networking thing that I had to mess with. It is documented here: https://tonyho.net/jekyll-docker-windows-and-0-0-0-0/

2020-07-19 18:21 UTC, jrbaxter0 commented on _posts/2020-07-10-f20_callout.md
> +In consideration of recent events with Covid-19, Purdue ARC has decided to host the Fall 2020 callout virtually. Upon release, students will be able to view the callout in an uploaded YouTube video a
I'm down for the 17th. I think we should still do a live webex one. Let's plan for the 31st, so that it is after the first week.

2020-07-19 18:40 UTC, jrbaxter0 approved these changes

2020-07-19 18:41 UTC, jrbaxter0 commented
I'm happy with the way things are now, but I also re-worded some things. Pls confirm you're still good with it.

2020-07-20 20:03 UTC, merged