Member update
purdue-arc/purdue-arc.github.io pull request #5
Opened 2020-07-20 22:16 UTC by hmcty

Updated members list, added past members section, added my photo

2020-07-21 02:05 UTC, jrbaxter0 requested changes
I think normally .png files are preferred, but I don't care that much. I would like to fix the VP issue though and at least briefly look into this gap thing.

2020-07-21 02:05 UTC, jrbaxter0 commented on _data/members.yml
> +    position: Vice President
VP is no longer VP

2020-07-21 02:05 UTC, jrbaxter0 commented on _pages/members.md
> +# Past Members
I never got this to work right. I see a gap on my end. Do you too?

2020-07-21 15:43 UTC, hmcty commented on _pages/members.md
> +# Past Members
It's an issue directly related to the "past members" header. I tried debugging for a little bit but to no avail. We can dig deeper, create a separate past-members page, or say good enough. Thoughts?

2020-07-21 15:50 UTC, jrbaxter0 commented on _pages/members.md
> +# Past Members
That's what I found too. Let's make an Issue just to track this, and only display current members for now. You can comment or delete the past members stuff in the page, but leave the yaml file as is

2020-07-21 15:53 UTC, hmcty commented
Left out previous members but fixed VP issue. I'll go ahead and create issues for the gap and image formatting.

2020-07-22 00:11 UTC, jrbaxter0 approved these changes

2020-07-22 00:11 UTC, merged